### ISSUE TITLE
Translation, saving bug? and usage

### ISSUE THREAD

**Issue by fourroses666** [mnoskov/customizer#1]
Hi MNoskov, thanks for sharing your plugin.

I noticed that when choose a color and save, it doesn't save the changes.
Can you please give instructions how to use the selected colors in the template. Grab it like [+primary_color+] ?

Don't know if you want to make this multilanguage.
If so, I have translated the text;

_RU - EN - NL_

**settings.php:**

Основные - Basic - Hoofd
Основной цвет - Primary color - Hoofdkleur
Цвет кнопок - Button color - Knop kleur
Переключатель - Switch - Omschakelen
Изображения - Images - Afbeeldingen
Главная страница - Home page - Beginpagina
Шапка - Header - Header
Фон меню в шапке - Background of the menu - Achtergrond van het menu
Основной цвет - Main color - Hoofd kleur
Цвет кнопок - Button color - Knop kleur

**panel.tpl:**

Сохранить - Save - Opslaan
Настройки - Settings - Instellingen

**Comment by mnoskov** [comment]
I'm using this plugin in conjunction with plugin "evo-less", which reads less-variables from json file, so it's way I'm using colors in CSS.

Also plugin on page init creates placeholders with`customizer_` prefix (`customizer_primary_color`).

Do you set path to json file to save?

**Comment by fourroses666** [comment]
It couldn't find the .json file, now saving works.
Didn't know it was used with evo-less. Thought it had placeholders just like ClientSettings.

I need to think about what I actually want, I have a project still in progress. I think showing ClientSettings on the frontpage would be the best for me. I don't know how to use LESS.

**Comment by mnoskov** [comment]
It had placeholders, you can do like this:
```
<style>
   body {
      background-color: [+customizer_primary_color+];
   }
</style>
```
But don't forget about cache. All template contents will be cached, so this code must be in uncached snippet.

**Comment by fourroses666** [comment]
Nice, that works, thanks.
